version: '3.3'

services:
  postgres:
    image: postgres
    container_name: cscl_db
    ports: 
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=cscl
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./seed/:/docker-entrypoint-initdb.d/:ro
  api:
    build: .
    container_name: cscl_api
    ports:
      - 5000:5000
    environment:
      - FLASK_APP=cscl_api.app.py
      - FLASK_ENV=development
      - DATABASE_URL=postgresql://postgres:postgres@192.168.99.100/cscl
    volumes:
      - ./cscl_api:/usr/src/app/cscl_api
volumes:
  postgres_data: